spring:
  jmx:
    default-domain: mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.195.112:3306/tgy?useUnicode=true&characterEncoding=utf-8
    username: tgymysql
    password: Tgymysql123@
mybatis:
  # mybatis配置实体类的路径
  type-aliases-package: com.hwj.tgy.entity
  # mybatis配置mapper.xml路径
  mapper-locations: mappers