spring:
  jmx:
    default-domain: mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  # 指定实体类包路径
  typeAliasesPackage: com.hwj.tgy.entity
  # 指定xml文件扫描路径
  mapper-locations: classpath*:mapper/*.xml